// <auto-generated />
using System;
using MatchdayAnalyzer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatchdayAnalyzer.Migrations
{
    [DbContext(typeof(MatchdayAnalyzerContext))]
    [Migration("20230922093824_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameTeam", b =>
                {
                    b.Property<int>("GamesId")
                        .HasColumnType("int");

                    b.Property<int>("TeamsListId")
                        .HasColumnType("int");

                    b.HasKey("GamesId", "TeamsListId");

                    b.HasIndex("TeamsListId");

                    b.ToTable("GameTeam");
                });

            modelBuilder.Entity("MatchdayAnalyzer.Models.ClassModels.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("MatchdayAnalyzer.Models.ClassModels.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttendanceId")
                        .HasColumnType("int");

                    b.Property<int?>("AwayTeamScore")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HomeTeamScore")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("OpponentTeam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("MatchdayAnalyzer.Models.ClassModels.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("MatchGoals")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("MatchdayAnalyzer.Models.ClassModels.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttendanceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int?>("TotalGoals")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceId");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MatchdayAnalyzer.Models.ClassModels.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("MatchdayAnalyzer.Models.ClassModels.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("GameTeam", b =>
                {
                    b.HasOne("MatchdayAnalyzer.Models.ClassModels.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatchdayAnalyzer.Models.ClassModels.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MatchdayAnalyzer.Models.ClassModels.Game", b =>
                {
                    b.HasOne("MatchdayAnalyzer.Models.ClassModels.Attendance", "Attendance")
                        .WithMany("Games")
                        .HasForeignKey("AttendanceId");

                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("MatchdayAnalyzer.Models.ClassModels.Goal", b =>
                {
                    b.HasOne("MatchdayAnalyzer.Models.ClassModels.Game", "Game")
                        .WithMany("GoalList")
                        .HasForeignKey("GameId");

                    b.HasOne("MatchdayAnalyzer.Models.ClassModels.Player", "player")
                        .WithMany("Goals")
                        .HasForeignKey("PlayerId");

                    b.Navigation("Game");

                    b.Navigation("player");
                });

            modelBuilder.Entity("MatchdayAnalyzer.Models.ClassModels.Player", b =>
                {
                    b.HasOne("MatchdayAnalyzer.Models.ClassModels.Attendance", "Attendance")
                        .WithMany("Players")
                        .HasForeignKey("AttendanceId");

                    b.HasOne("MatchdayAnalyzer.Models.ClassModels.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId");

                    b.Navigation("Attendance");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("MatchdayAnalyzer.Models.ClassModels.Team", b =>
                {
                    b.HasOne("MatchdayAnalyzer.Models.ClassModels.Season", "Seasons")
                        .WithMany("Teams")
                        .HasForeignKey("SeasonId");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("MatchdayAnalyzer.Models.ClassModels.Attendance", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("MatchdayAnalyzer.Models.ClassModels.Game", b =>
                {
                    b.Navigation("GoalList");
                });

            modelBuilder.Entity("MatchdayAnalyzer.Models.ClassModels.Player", b =>
                {
                    b.Navigation("Goals");
                });

            modelBuilder.Entity("MatchdayAnalyzer.Models.ClassModels.Season", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("MatchdayAnalyzer.Models.ClassModels.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
